[package]
name = "dfx-extension"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.28", features = ["derive", "env"] }
tokio = { version = "1.43.0", features = ["full"] }
